When mode 4 is active ABI captures full disk images every 5 minutes but no other scans. We should extact missing CONUS scan data from this when it's running

In [2]:
import numpy as np
from numpy import ma
import pandas as pd
import xarray as xr
from datetime import datetime, timedelta
from dateutil.parser import parse as parse_date
from tobac_flow import io

In [3]:
# Load files
goes_data_path = '../data/GOES16'
date = datetime(2018,6,19,17)

abiC_files = sorted(io.find_abi_files(date, satellite=16, product='MCMIP', view='C', mode=3, 
                               save_dir=goes_data_path, 
                               replicate_path=True, check_download=True, 
                               n_attempts=1, download_missing=True))

abiF_files = sorted(io.find_abi_files(date, satellite=16, product='MCMIP', view='F', mode=3, 
                               save_dir=goes_data_path, 
                               replicate_path=True, check_download=True, 
                               n_attempts=1, download_missing=True))

print("CONUS files:", len(abiC_files))
print("Full disk files:", len(abiF_files))
      

CONUS files: 12
Full disk files: 4


In [4]:
abiC_ds = xr.open_dataset(abiC_files[0])
abiF_ds = xr.open_dataset(abiF_files[0])

In [5]:
abiC_ds.x

<xarray.DataArray 'x' (x: 2500)>
array([-0.101332, -0.101276, -0.10122 , ...,  0.0385  ,  0.038556,  0.038612],
      dtype=float32)
Coordinates:
    t        datetime64[ns] ...
  * x        (x) float32 -0.1013 -0.1013 -0.1012 ... 0.0385 0.03856 0.03861
    y_image  float32 ...
    x_image  float32 ...
Attributes:
    units:          rad
    axis:           X
    long_name:      GOES fixed grid projection x-coordinate
    standard_name:  projection_x_coordinate

In [6]:
abiF_ds.x

<xarray.DataArray 'x' (x: 5424)>
array([-0.151844, -0.151788, -0.151732, ...,  0.151732,  0.151788,  0.151844],
      dtype=float32)
Coordinates:
    t        datetime64[ns] ...
  * x        (x) float32 -0.1518 -0.1518 -0.1517 ... 0.1517 0.1518 0.1518
    y_image  float32 ...
    x_image  float32 ...
Attributes:
    units:          rad
    axis:           X
    long_name:      GOES fixed grid projection x-coordinate
    standard_name:  projection_x_coordinate

In [8]:
abiF_ds.sel(x=abiC_ds.x, y=abiC_ds.y, method="nearest")

<xarray.Dataset>
Dimensions:                                 (band: 1, number_of_image_bounds: 2, number_of_time_bounds: 2, x: 2500, y: 1500)
Coordinates:
    t                                       datetime64[ns] 2018-06-19T17:06:0...
  * y                                       (y) float32 0.1282 ... 0.04427
  * x                                       (x) float32 -0.1013 ... 0.03861
    y_image                                 float32 0.0
    x_image                                 float32 0.0
    band_wavelength_C01                     (band) float32 ...
    band_wavelength_C02                     (band) float32 ...
    band_wavelength_C03                     (band) float32 ...
    band_wavelength_C04                     (band) float32 ...
    band_wavelength_C05                     (band) float32 ...
    band_wavelength_C06                     (band) float32 ...
    band_wavelength_C07                     (band) float32 ...
    band_wavelength_C08                     (band) float32 ...
    band_wavelength_C09                     (band) float32 ...
    band_wavelength_C10                     (band) float32 ...
    band_wavelength_C11                     (band) float32 ...
    band_wavelength_C12                     (band) float32 ...
    band_wavelength_C13                     (band) float32 ...
    band_wavelength_C14                     (band) float32 ...
    band_wavelength_C15                     (band) float32 ...
    band_wavelength_C16                     (band) float32 ...
    band_id_C01                             (band) int8 ...
    band_id_C02                             (band) int8 ...
    band_id_C03                             (band) int8 ...
    band_id_C04                             (band) int8 ...
    band_id_C05                             (band) int8 ...
    band_id_C06                             (band) int8 ...
    band_id_C07                             (band) int8 ...
    band_id_C08                             (band) int8 ...
    band_id_C09                             (band) int8 ...
    band_id_C10                             (band) int8 ...
    band_id_C11                             (band) int8 ...
    band_id_C12                             (band) int8 ...
    band_id_C13                             (band) int8 ...
    band_id_C14                             (band) int8 ...
    band_id_C15                             (band) int8 ...
    band_id_C16                             (band) int8 ...
Dimensions without coordinates: band, number_of_image_bounds, number_of_time_bounds
Data variables:
    CMI_C01                                 (y, x) float32 ...
    DQF_C01                                 (y, x) float32 ...
    CMI_C02                                 (y, x) float32 ...
    DQF_C02                                 (y, x) float32 ...
    CMI_C03                                 (y, x) float32 ...
    DQF_C03                                 (y, x) float32 ...
    CMI_C04                                 (y, x) float32 ...
    DQF_C04                                 (y, x) float32 ...
    CMI_C05                                 (y, x) float32 ...
    DQF_C05                                 (y, x) float32 ...
    CMI_C06                                 (y, x) float32 ...
    DQF_C06                                 (y, x) float32 ...
    CMI_C07                                 (y, x) float32 ...
    DQF_C07                                 (y, x) float32 ...
    CMI_C08                                 (y, x) float32 ...
    DQF_C08                                 (y, x) float32 ...
    CMI_C09                                 (y, x) float32 ...
    DQF_C09                                 (y, x) float32 ...
    CMI_C10                                 (y, x) float32 ...
    DQF_C10                                 (y, x) float32 ...
    CMI_C11                                 (y, x) float32 ...
    DQF_C11                                 (y, x) float32 ...
    CMI_C12                                 (y,

In [10]:
abiF_ds.sel(x=slice(abiC_ds.x[0], abiC_ds.x[-1]), y=slice(abiC_ds.y[0], abiC_ds.y[-1]))

<xarray.Dataset>
Dimensions:                                 (band: 1, number_of_image_bounds: 2, number_of_time_bounds: 2, x: 2499, y: 1499)
Coordinates:
    t                                       datetime64[ns] 2018-06-19T17:06:0...
  * y                                       (y) float32 0.1282 ... 0.04432
  * x                                       (x) float32 -0.1013 ... 0.03856
    y_image                                 float32 0.0
    x_image                                 float32 0.0
    band_wavelength_C01                     (band) float32 ...
    band_wavelength_C02                     (band) float32 ...
    band_wavelength_C03                     (band) float32 ...
    band_wavelength_C04                     (band) float32 ...
    band_wavelength_C05                     (band) float32 ...
    band_wavelength_C06                     (band) float32 ...
    band_wavelength_C07                     (band) float32 ...
    band_wavelength_C08                     (band) float32 ...
    band_wavelength_C09                     (band) float32 ...
    band_wavelength_C10                     (band) float32 ...
    band_wavelength_C11                     (band) float32 ...
    band_wavelength_C12                     (band) float32 ...
    band_wavelength_C13                     (band) float32 ...
    band_wavelength_C14                     (band) float32 ...
    band_wavelength_C15                     (band) float32 ...
    band_wavelength_C16                     (band) float32 ...
    band_id_C01                             (band) int8 ...
    band_id_C02                             (band) int8 ...
    band_id_C03                             (band) int8 ...
    band_id_C04                             (band) int8 ...
    band_id_C05                             (band) int8 ...
    band_id_C06                             (band) int8 ...
    band_id_C07                             (band) int8 ...
    band_id_C08                             (band) int8 ...
    band_id_C09                             (band) int8 ...
    band_id_C10                             (band) int8 ...
    band_id_C11                             (band) int8 ...
    band_id_C12                             (band) int8 ...
    band_id_C13                             (band) int8 ...
    band_id_C14                             (band) int8 ...
    band_id_C15                             (band) int8 ...
    band_id_C16                             (band) int8 ...
Dimensions without coordinates: band, number_of_image_bounds, number_of_time_bounds
Data variables:
    CMI_C01                                 (y, x) float32 ...
    DQF_C01                                 (y, x) float32 ...
    CMI_C02                                 (y, x) float32 ...
    DQF_C02                                 (y, x) float32 ...
    CMI_C03                                 (y, x) float32 ...
    DQF_C03                                 (y, x) float32 ...
    CMI_C04                                 (y, x) float32 ...
    DQF_C04                                 (y, x) float32 ...
    CMI_C05                                 (y, x) float32 ...
    DQF_C05                                 (y, x) float32 ...
    CMI_C06                                 (y, x) float32 ...
    DQF_C06                                 (y, x) float32 ...
    CMI_C07                                 (y, x) float32 ...
    DQF_C07                                 (y, x) float32 ...
    CMI_C08                                 (y, x) float32 ...
    DQF_C08                                 (y, x) float32 ...
    CMI_C09                                 (y, x) float32 ...
    DQF_C09                                 (y, x) float32 ...
    CMI_C10                                 (y, x) float32 ...
    DQF_C10                                 (y, x) float32 ...
    CMI_C11                                 (y, x) float32 ...
    DQF_C11                                 (y, x) float32 ...
    CMI_C12                                 (y,

In [13]:
np.where(np.isclose(abiF_ds.x,abiC_ds.x[0]))

(array([902]),)

In [11]:
np.where(np.isclose(abiF_ds.y,abiC_ds.y[0]))

(array([422]),)

In [11]:
abiF_ds.sel(x=abiC_ds.x, y=abiC_ds.y, method="nearest").x

<xarray.DataArray 'x' (x: 2500)>
array([-0.101332, -0.101276, -0.10122 , ...,  0.0385  ,  0.038556,  0.038612],
      dtype=float32)
Coordinates:
    t        datetime64[ns] 2018-06-19T17:06:02.290364928
  * x        (x) float32 -0.1013 -0.1013 -0.1012 ... 0.0385 0.03856 0.03861
    y_image  float32 0.0
    x_image  float32 0.0
Attributes:
    units:          rad
    axis:           X
    long_name:      GOES fixed grid projection x-coordinate
    standard_name:  projection_x_coordinate

In [12]:
abiC_ds.x

<xarray.DataArray 'x' (x: 2500)>
array([-0.101332, -0.101276, -0.10122 , ...,  0.0385  ,  0.038556,  0.038612],
      dtype=float32)
Coordinates:
    t        datetime64[ns] 2018-06-19T17:03:43.273992960
  * x        (x) float32 -0.1013 -0.1013 -0.1012 ... 0.0385 0.03856 0.03861
    y_image  float32 0.08624
    x_image  float32 -0.03136
Attributes:
    units:          rad
    axis:           X
    long_name:      GOES fixed grid projection x-coordinate
    standard_name:  projection_x_coordinate